### ISSUE TITLE
Shitton of warnings when debugging iobroker.javascript

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/dev-server#115]
![grafik](https://user-images.githubusercontent.com/17641229/134805047-0c62f069-cf02-4395-a816-1198ec675010.png)
This goes on for a while.

**Comment by AlCalzone** [comment]
Also maybe `node_modules` should be exempt from FS watching:
![grafik](https://user-images.githubusercontent.com/17641229/134805107-49ffe404-5f19-4f0a-ac72-447f9c685743.png)

**Comment by UncleSamSwiss** [comment]
1. WTF? Why is there a node_modules directory in src? Oh yes right, it's the weird way of doing React... I'm not sure if we should even support such adapters because we will also not be able to properly rebuild the UI let alone do hot reload.
2. The watch excludes these files already as you can see in the `(before/after): 1/0`

**Comment by AlCalzone** [comment]
> Oh yes right, it's the weird way of doing React...

Good point. But ignoring node_modules altogether shouldn't be too bad?
dev-server run works fine, just watching fails.
