### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by XSDiVer** [ioBroker/dev-server#285]
[log-connect ECONNREFUSED.txt](https://github.com/ioBroker/dev-server/files/9277237/log-connect.ECONNREFUSED.txt)

Hello,

I need to restart my def-server often, because it crashes at starting.

I attached the log.

Thank you for helping.

XSD

**Comment by ciddi89** [comment]
Hi,

I guess I have the same issue when I compare the log of XSDiVer and mine. Sometime I need an second or third start and then it runs. I hope the Log is helping.

[dev-server-start-log.txt](https://github.com/ioBroker/dev-server/files/9440129/dev-server-start-log.txt)

**Comment by ciddi89** [comment]
Okay I think I found out why I get this error. When I close the connection (ctrl + c) and try to reopen the connection with dev-server watch but the browser is still open and try all time to reload the admin in this time when you try to use watch, then it's not possible to start the dev server. So the fix is -> Close the tab/window where the browser tries to reload the admin interface of dev-server.

**Comment by Apollon77** [comment]
The 0.6.0 of dev-server just release earlier today should also fix this
